version: "3.9"
services:

  polling-api:
    build: ../services/polling/
    expose:
      - "80"
    ports:
      - "8080:80"
    extra_hosts:
      - "CESARDLSURFBOOK:10.0.75.1"

  identity-api:
    build: ../services/identity/identityservice/
    expose:
      - "80"
    ports:
      - "8082:80"
    extra_hosts:
      - "CESARDLSURFBOOK:10.0.75.1"

  web:
    build: ../services/lobby/
    environment:
      - DB_LOCATION=sql
      - DB_USER=db_user
      - DB_PASSWORD=pwd
      - DB_NAME=db
    expose:
      - "80"
    ports:
       - "8083:80"
    extra_hosts:
       - "CESARDLSURFBOOK:10.0.75.1"


